---
# tasks file for prod
- name: install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - default-jdk
      - maven
      - git
- name: Ensure git clonned
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: /tmp/boxfuse-sample-java-war-hello

- name: Run mvn package
  command: chdir=/tmp/boxfuse-sample-java-war-hello mvn package

- name: Copy
  fetch:
    src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dest: ~/.ansible/roles/web/files/
    flat: yes
    
